# Generated by Django 5.2 on 2025-04-10 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=255)),
                ('hersteller_bezeichnung', models.CharField(blank=True, max_length=255)),
                ('preis_brutto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quelle', models.CharField(blank=True, max_length=255)),
                ('bestell_nr', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('lieferung', 'Lieferung'), ('verbrauch', 'Verbrauch'), ('verlust', 'Verlust'), ('korrektur', 'Korrektur')], max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.material')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workshop')),
            ],
        ),
    ]
