# Generated by Django 5.2 on 2025-04-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='preis_brutto',
        ),
        migrations.RemoveField(
            model_name='material',
            name='quelle',
        ),
        migrations.AddField(
            model_name='deliveryitem',
            name='preis_pro_stueck',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='deliveryitem',
            name='quelle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='material',
            name='bild',
            field=models.ImageField(blank=True, null=True, upload_to='material_images/'),
        ),
    ]
