# Generated by Django 5.2 on 2025-04-11 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_remove_material_preis_brutto_remove_material_quelle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bestellt_am', models.DateField()),
                ('angekommen_am', models.DateField(blank=True, null=True)),
                ('versandkosten', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notiz', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='deliveryitem',
            name='preis_pro_stueck',
        ),
        migrations.RemoveField(
            model_name='deliveryitem',
            name='quelle',
        ),
        migrations.AddField(
            model_name='delivery',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.order'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preis_pro_stueck', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preis_pro_stueck_mit_versand', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quelle', models.CharField(blank=True, max_length=255)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.material')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='materials.order')),
            ],
        ),
    ]
