# Generated by Django 5.2 on 2025-04-25 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('materials', '0003_order_remove_deliveryitem_preis_pro_stueck_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialmovement',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='materialmovement',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
