# Generated by Django 5.2 on 2025-04-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_materialtransfer_materialtransferitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialmovement',
            name='change_type',
            field=models.CharField(choices=[('lieferung', 'Lieferung'), ('verbrauch', 'Verbrauch'), ('verlust', 'Verlust'), ('korrektur', 'Korrektur'), ('transfer', 'Transfer')], max_length=50),
        ),
    ]
