# Generated by Django 5.2.8 on 2025-11-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_materialcategory_material_alternatives_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialmovement',
            name='change_type',
            field=models.CharField(choices=[('lieferung', 'Lieferung'), ('verbrauch', 'Verbrauch'), ('verlust', 'Verlust'), ('korrektur', 'Korrektur'), ('transfer', 'Transfer'), ('inventur', 'Inventur')], max_length=50),
        ),
    ]
