# Generated by Django 5.2.8 on 2025-11-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_alter_materialmovement_change_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='deprecated',
            field=models.BooleanField(default=False, help_text='Material ist veraltet und wird nicht mehr verwendet'),
        ),
    ]
