# Generated by Django 5.2 on 2025-11-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0009_material_deprecated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True)),
                ('kundenkonto', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='material',
            name='suppliers',
            field=models.ManyToManyField(blank=True, related_name='materials', to='materials.supplier'),
        ),
    ]
