# Generated by Django 5.2 on 2025-11-26 20:32

from django.db import migrations


def backfill_supplier_and_order_number(apps, schema_editor):
    """Create fallback supplier and populate order_number for existing orders"""
    Order = apps.get_model('materials', 'Order')
    Supplier = apps.get_model('materials', 'Supplier')
    
    # Create or get fallback supplier for existing orders
    default_supplier, created = Supplier.objects.get_or_create(
        name='Unbekannter Lieferant',
        defaults={
            'url': '',
            'kundenkonto': '',
            'notes': 'Automatisch erstellt für bestehende Bestellungen ohne Lieferanten',
            'is_active': False
        }
    )
    
    # Update all orders without supplier
    orders_without_supplier = Order.objects.filter(supplier__isnull=True)
    for order in orders_without_supplier:
        order.supplier = default_supplier
        
        # Generate order_number if empty
        if not order.order_number:
            order.order_number = f'ORD-LEGACY-{order.id:05d}'
        
        order.save()


def reverse_backfill(apps, schema_editor):
    """Remove fallback supplier on rollback (optional)"""
    Supplier = apps.get_model('materials', 'Supplier')
    Supplier.objects.filter(name='Unbekannter Lieferant').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0011_order_order_number_order_supplier_and_more'),
    ]

    operations = [
        migrations.RunPython(
            backfill_supplier_and_order_number,
            reverse_backfill
        ),
    ]
