# Generated by Django 5.2 on 2025-11-26 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0013_finalize_order_supplier_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='angekommen_am',
        ),
    ]
