# Generated by Django 5.2 on 2025-11-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0014_remove_order_angekommen_am'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_historical',
            field=models.BooleanField(default=False, help_text='Historische Bestellungen haben keine Auswirkung auf den Materialbestand'),
        ),
    ]
