# Generated by Django 5.2 on 2025-11-26 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0015_add_is_historical_to_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='is_historical',
            field=models.BooleanField(default=False, help_text='Historische Lieferungen haben keine Auswirkung auf den Materialbestand'),
        ),
    ]
