# Generated by Django 5.2 on 2025-11-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0016_add_is_historical_to_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivered_at',
            field=models.DateField(blank=True, help_text='Datum der tatsächlichen Lieferung', null=True),
        ),
    ]
