# Generated by Django 5.2 on 2025-11-26 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0017_add_delivered_at_to_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='mwst_satz',
            field=models.DecimalField(decimal_places=2, default=19.0, help_text='MwSt.-Satz in Prozent (z.B. 19.00 für 19%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='preis_pro_stueck',
            field=models.DecimalField(decimal_places=2, help_text='Netto-Preis pro Stück', max_digits=10),
        ),
    ]
