# Generated by Django 5.2 on 2025-11-26 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0018_add_mwst_satz_to_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='versandkosten_mwst_satz',
            field=models.DecimalField(decimal_places=2, default=19.0, help_text='MwSt.-Satz für Versandkosten in Prozent', max_digits=5),
        ),
    ]
