# Generated by Django 5.2 on 2025-11-26 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0019_add_versandkosten_mwst_satz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='preis_pro_stueck',
            field=models.DecimalField(decimal_places=5, help_text='Netto-Preis pro Stück', max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='preis_pro_stueck_mit_versand',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
    ]
