# Generated by Django 5.2 on 2025-11-26 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0020_increase_price_decimal_places'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='quelle',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='artikelnummer',
            field=models.CharField(blank=True, help_text='Artikelnummer des Lieferanten', max_length=255, verbose_name='Artikelnummer'),
        ),
    ]
