# Generated by Django 5.2 on 2025-11-27 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0021_rename_quelle_to_artikelnummer'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialSupplierPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=5, help_text='Preis pro Einheit (netto)', max_digits=10)),
                ('valid_from', models.DateField(help_text='Ab wann dieser Preis gültig ist')),
                ('note', models.TextField(blank=True, help_text='Optional: Notizen zum Preis (z.B. Mindestbestellmenge)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_prices', to='materials.material')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_prices', to='materials.supplier')),
            ],
            options={
                'verbose_name': 'Material-Lieferanten-Preis',
                'verbose_name_plural': 'Material-Lieferanten-Preise',
                'ordering': ['-valid_from'],
                'unique_together': {('material', 'supplier', 'valid_from')},
            },
        ),
    ]
