# Generated by Django 5.2 on 2025-11-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0022_materialsupplierprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialsupplierprice',
            name='material_url',
            field=models.URLField(blank=True, help_text='URL zum Material beim Lieferanten (z.B. Produktseite)', max_length=500, null=True),
        ),
    ]
