# Generated by Django 5.2 on 2025-11-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0023_materialsupplierprice_material_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='supplier_url',
            field=models.URLField(blank=True, help_text='URL zur Bestellung beim Lieferanten (z.B. Link zur Bestellseite)', max_length=500, verbose_name='Lieferanten-URL'),
        ),
    ]
