# Generated by Django 5.2 on 2025-11-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0024_add_supplier_url_to_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='material_url',
            field=models.URLField(blank=True, help_text='URL zum Material beim Lieferanten (z.B. Produktseite)', max_length=500, verbose_name='Material-URL'),
        ),
    ]
