# Generated by Django 5.2 on 2025-11-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('de', 'Deutsch'), ('en', 'English'), ('fr', 'Français'), ('es', 'Español'), ('it', 'Italiano'), ('nl', 'Nederlands')], default='de', max_length=5, verbose_name='Sprache')),
                ('template_type', models.CharField(choices=[('order_shipped', 'Bestellung versendet'), ('order_completed', 'Bestellung abgeschlossen'), ('order_reminder', 'Erinnerung')], default='order_shipped', max_length=50, verbose_name='Template-Typ')),
                ('name', models.CharField(help_text='Interner Name zur Identifikation', max_length=100, verbose_name='Template-Name')),
                ('subject', models.CharField(help_text='E-Mail Betreff mit Platzhaltern', max_length=255, verbose_name='Betreff')),
                ('body', models.TextField(help_text='E-Mail Inhalt mit Platzhaltern', verbose_name='E-Mail Text')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('is_default', models.BooleanField(default=False, help_text='Wird automatisch für diese Sprache verwendet', verbose_name='Standard-Template')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'E-Mail Template',
                'verbose_name_plural': 'E-Mail Templates',
                'ordering': ['language', 'template_type', 'name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('language', 'template_type'), name='unique_default_template_per_language_type')],
            },
        ),
    ]
