# Generated by Django 5.2 on 2025-11-27 21:20

from django.db import migrations


def add_default_templates(apps, schema_editor):
    EmailTemplate = apps.get_model('shopbridge', 'EmailTemplate')

    # Deutsches Template
    EmailTemplate.objects.create(
        language='de',
        template_type='order_shipped',
        name='Standard Versandbenachrichtigung (Deutsch)',
        subject='[SD-Link] Dein Adapter ist unterwegs!',
        body="""Hallo {{first_name}},

der Adapter ist auf dem Weg zu Dir.

Wenn du die Sendung verfolgen möchtest, benutze bitte diesen Link:
{{tracking_link}}

Falls irgendwelche Fragen, Probleme oder Hinweise sind, bitte nicht zögern und an mich wenden.

Fliegende Grüße

Wir würden uns sehr über ein Foto von der erfolgreichen Installation freuen.
Falls Du zustimmst würden wir das dann in der „Galerie der Installationen" veröffentlichen, natürlich ohne jeden Bezug auf Deine Person oder das Flugzeug.

{{signature}}""",
        is_active=True,
        is_default=True,
    )

    # Englisches Template
    EmailTemplate.objects.create(
        language='en',
        template_type='order_shipped',
        name='Standard Shipping Notification (English)',
        subject='[SD-Link] Your SD-Link Adapter is on its way',
        body="""Hello {{first_name}},

The adapter is on its way to you.

Please note that we have experienced delivery times to the UK of up to 14 days recently. Thank you for your patience.

If you have any questions, issues, or suggestions, please don't hesitate to contact me.

Best regards

We'd really appreciate a photo of the successful installation.
If you agree, we'd be happy to publish it in our "Installation Gallery" — of course without any reference to you or your aircraft.

By the way — how did you hear about us?
We're always curious to learn where our customers found us.

{{signature}}""",
        is_active=True,
        is_default=True,
    )

    # Französisches Template
    EmailTemplate.objects.create(
        language='fr',
        template_type='order_shipped',
        name='Notification d\'expédition standard (Français)',
        subject='[SD-Link] Votre commande est en route !',
        body="""Bonjour {{first_name}},

L'adaptateur est en route vers toi.

Veuillez noter que nous avons constaté que les livraisons vers la France peuvent malheureusement prendre jusqu'à 14 jours en ce moment. Merci pour ta patience.

Si tu as des questions, des problèmes ou des remarques, n'hésite pas à me contacter.

Cordialement

Nous serions ravis de recevoir une photo de l'installation réussie.
Avec ton accord, nous pourrions la publier dans notre « Galerie des installations », bien entendu sans aucune référence à ta personne ou à ton avion.

{{signature}}""",
        is_active=True,
        is_default=True,
    )

    # Polnisches Template
    EmailTemplate.objects.create(
        language='pl',
        template_type='order_shipped',
        name='Powiadomienie o wysyłce (Polski)',
        subject='[SD-Link] Twoje zamówienie jest w drodze!',
        body="""Cześć {{first_name}},

Adapter jest w drodze do Ciebie.

Śledź przesyłkę tutaj:
{{tracking_link}}

Dostawa do Polski zwykle trwa 10-14 dni roboczych.

Mamy małą prośbę: Czy po zainstalowaniu mógłbyś/mogłabyś wysłać nam zdjęcie swojej instalacji? Bardzo cieszymy się ze zdjęć od naszych klientów - oczywiście za Twoją zgodą.

Interesuje nas też, jak do nas trafiłeś/trafiłaś? Polecenie od znajomych, Google, media społecznościowe...?

Serdeczne pozdrowienia

{{signature}}""",
        is_active=True,
        is_default=True,
    )

    # Niederländisches Template
    EmailTemplate.objects.create(
        language='nl',
        template_type='order_shipped',
        name='Verzendnotificatie (Nederlands)',
        subject='[SD-Link] Je bestelling is onderweg!',
        body="""Hallo {{first_name}},

De adapter is onderweg naar jou.

Volg je pakket hier:
{{tracking_link}}

Levering naar Nederland duurt meestal 3-5 werkdagen.

We hebben een klein verzoek: Zou je na de installatie een foto van je installatie naar ons kunnen sturen? We zijn altijd blij met fotos van onze klanten - uiteraard met jouw toestemming.

We zijn ook benieuwd hoe je ons gevonden hebt? Aanbeveling van vrienden, Google, social media...?

Hartelijke groeten

{{signature}}""",
        is_active=True,
        is_default=True,
    )

    # Italienisches Template
    EmailTemplate.objects.create(
        language='it',
        template_type='order_shipped',
        name='Notifica di spedizione (Italiano)',
        subject='[SD-Link] Il tuo ordine è in arrivo!',
        body="""Ciao {{first_name}},

L'adattatore è in arrivo.

Traccia il tuo pacco qui:
{{tracking_link}}

La consegna in Italia richiede solitamente 10-14 giorni lavorativi.

Abbiamo una piccola richiesta: Potresti inviarci una foto della tua installazione dopo averla completata? Siamo sempre felici di ricevere foto dai nostri clienti - ovviamente con il tuo consenso.

Ci piacerebbe anche sapere come ci hai trovato? Raccomandazione di amici, Google, social media...?

Cordiali saluti

{{signature}}""",
        is_active=True,
        is_default=True,
    )

    # Spanisches Template
    EmailTemplate.objects.create(
        language='es',
        template_type='order_shipped',
        name='Notificación de envío (Español)',
        subject='[SD-Link] ¡Tu pedido está en camino!',
        body="""Hola {{first_name}},

El adaptador está en camino hacia ti.

Sigue tu envío aquí:
{{tracking_link}}

La entrega a España suele tardar 10-14 días laborables.

Tenemos una pequeña petición: ¿Podrías enviarnos una foto de tu instalación después de completarla? Siempre nos alegra recibir fotos de nuestros clientes - por supuesto, con tu consentimiento.

También nos gustaría saber cómo nos encontraste: ¿Recomendación de amigos, Google, redes sociales...?

Saludos cordiales

{{signature}}""",
        is_active=True,
        is_default=True,
    )

    # Tschechisches Template
    EmailTemplate.objects.create(
        language='cs',
        template_type='order_shipped',
        name='Oznámení o odeslání (Čeština)',
        subject='[SD-Link] Vaše objednávka byla odeslána!',
        body="""Dobrý den {{first_name}},

Adaptér je na cestě k Vám.

Sledujte zásilku zde:
{{tracking_link}}

Doručení do České republiky obvykle trvá 10-14 pracovních dnů.

Máme malou prosbu: Mohli byste nám po instalaci poslat fotografii? Vždy nás těší fotografie od našich zákazníků - samozřejmě s Vaším souhlasem.

Také by nás zajímalo, jak jste nás našli? Doporučení od přátel, Google, sociální sítě...?

S přátelským pozdravem

{{signature}}""",
        is_active=True,
        is_default=True,
    )


def remove_default_templates(apps, schema_editor):
    EmailTemplate = apps.get_model('shopbridge', 'EmailTemplate')
    EmailTemplate.objects.filter(is_default=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('shopbridge', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_default_templates, remove_default_templates),
    ]
