# Generated by Django 5.2.8 on 2025-11-27 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopbridge', '0002_add_default_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSerialNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('woocommerce_order_id', models.IntegerField(db_index=True, verbose_name='WooCommerce Bestellungs-ID')),
                ('woocommerce_order_number', models.CharField(help_text='Die Bestellnummer aus WooCommerce (z.B. #12345)', max_length=50, verbose_name='WooCommerce Bestellnummer')),
                ('serial_number', models.CharField(help_text='Seriennummer des versendeten Adapters', max_length=100, verbose_name='Seriennummer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Seriennummer',
                'verbose_name_plural': 'Seriennummern',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='language',
            field=models.CharField(choices=[('de', 'Deutsch'), ('en', 'English'), ('fr', 'Français'), ('es', 'Español'), ('it', 'Italiano'), ('nl', 'Nederlands'), ('pl', 'Polski'), ('cs', 'Čeština')], default='de', max_length=5, verbose_name='Sprache'),
        ),
    ]
