# Generated by Django 5.2.8 on 2025-11-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopbridge', '0003_add_order_serial_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DHLLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Sendungsnummer')),
                ('woocommerce_order_id', models.IntegerField(db_index=True, verbose_name='WooCommerce Bestellungs-ID')),
                ('woocommerce_order_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='WooCommerce Bestellnummer')),
                ('product', models.CharField(choices=[('V01PAK', 'DHL Paket'), ('V62KP', 'DHL Kleinpaket'), ('V62WP', 'Warenpost National'), ('V66WPI', 'Warenpost International')], default='V62KP', max_length=20, verbose_name='DHL Produkt')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kundenreferenz')),
                ('label_pdf_base64', models.TextField(help_text='Das PDF-Label in Base64-Kodierung', verbose_name='Label PDF (Base64)')),
                ('label_format', models.CharField(default='PDF', max_length=20, verbose_name='Label Format')),
                ('print_format', models.CharField(default='910-300-356', max_length=20, verbose_name='Druckformat')),
                ('routing_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Routing Code')),
                ('status', models.CharField(choices=[('created', 'Erstellt'), ('printed', 'Gedruckt'), ('shipped', 'Versendet'), ('deleted', 'Gelöscht')], default='created', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'DHL Label',
                'verbose_name_plural': 'DHL Labels',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['woocommerce_order_id'], name='shopbridge__woocomm_959e94_idx'), models.Index(fields=['status', 'created_at'], name='shopbridge__status_c2cabc_idx')],
            },
        ),
    ]
