# Generated by Django 5.2 on 2025-11-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopbridge', '0004_add_dhl_label_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingCountryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(help_text='2-stelliger ISO-Ländercode (z.B. DE, AT, CH)', max_length=2, unique=True, verbose_name='Ländercode (ISO)')),
                ('country_name', models.CharField(help_text='Anzeigename des Landes', max_length=100, verbose_name='Ländername')),
                ('shipping_type', models.CharField(choices=[('dhl_product', 'DHL Produkt (Label erstellen)'), ('external_link', 'Externer Link (manuell)')], default='dhl_product', max_length=20, verbose_name='Versandart')),
                ('dhl_product', models.CharField(blank=True, choices=[('V62WP', 'Warenpost National'), ('V66WPI', 'Warenpost International'), ('V62KP', 'DHL Kleinpaket'), ('V01PAK', 'DHL Paket')], help_text='Nur relevant wenn Versandart = DHL Produkt', max_length=20, null=True, verbose_name='DHL Produkt')),
                ('external_link', models.URLField(blank=True, help_text='Link zur externen Versandseite (z.B. DHL Privatkunden)', max_length=500, null=True, verbose_name='Externer Link')),
                ('external_link_label', models.CharField(blank=True, default='Manuell versenden', help_text='Text für den Button/Link', max_length=100, null=True, verbose_name='Link-Beschriftung')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('notes', models.TextField(blank=True, help_text='Interne Notizen zur Konfiguration', null=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Versandkonfiguration',
                'verbose_name_plural': 'Versandkonfigurationen',
                'ordering': ['country_name'],
            },
        ),
    ]
