# Generated by Django 5.2 on 2025-11-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopbridge', '0005_add_shipping_country_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_identifier', models.CharField(help_text='SKU oder Produktname (z.B. SD-KRT2, SD-ATR833)', max_length=200, verbose_name='Produkt-Bezeichnung')),
                ('language', models.CharField(choices=[('de', 'Deutsch'), ('en', 'English'), ('fr', 'Français'), ('es', 'Español')], default='de', max_length=5, verbose_name='Sprache')),
                ('manual_type', models.CharField(choices=[('installation', 'Installationsanleitung'), ('configuration', 'Einrichtungsanleitung'), ('quickstart', 'Schnellstartanleitung'), ('other', 'Sonstiges')], default='installation', max_length=50, verbose_name='Anleitungstyp')),
                ('title', models.CharField(help_text='Angezeigter Titel der Anleitung', max_length=255, verbose_name='Titel')),
                ('pdf_url', models.URLField(help_text='Link zur PDF-Datei', max_length=500, verbose_name='PDF-URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('order', models.PositiveIntegerField(default=0, help_text='Kleinere Zahlen werden zuerst angezeigt', verbose_name='Reihenfolge')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produkthandbuch',
                'verbose_name_plural': 'Produkthandbücher',
                'ordering': ['product_identifier', 'language', 'order', 'title'],
            },
        ),
    ]
