# Generated by Django 5.2 on 2025-11-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopbridge', '0006_add_product_manual_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmanual',
            name='applies_to_all',
            field=models.BooleanField(default=False, help_text='Wenn aktiviert, wird dieses Handbuch bei jeder Bestellung angezeigt', verbose_name='Für alle Bestellungen'),
        ),
    ]
