# shopbridge/migrations/0008_populate_product_manuals.py
# Generated by Django 5.2 on 2025-11-28

from django.db import migrations


def populate_product_manuals(apps, schema_editor):
    """Populate product manuals with initial data (from sdlink.de download page)."""
    ProductManual = apps.get_model('shopbridge', 'ProductManual')

    # Lösche alle vorhandenen Handbücher
    ProductManual.objects.all().delete()

    manuals = [
        # =========================================================
        # KONFIGURATIONSANLEITUNGEN (applies_to_all=True)
        # -> erscheinen bei JEDER Bestellung
        # =========================================================

        # Deutsch
        {
            "product_identifier": "Einrichtungsanleitungen",
            "language": "de",
            "manual_type": "configuration",
            "title": "Anleitung Einrichtung neuer BLE Geräte in SkyDemon",
            "pdf_url": "https://sdlink.de/wp-content/uploads/2025/04/Wie-konfiguriere-ich-in-SkyDemon-einen-neuen-SD.pdf",
            "is_active": True,
            "order": 1,
            "applies_to_all": True,
        },
        {
            "product_identifier": "Einrichtungsanleitungen",
            "language": "de",
            "manual_type": "configuration",
            "title": "Anleitung Einrichtung neuer BLE Geräte in Sky-Map für Android",
            "pdf_url": "https://sdlink.de/wp-content/uploads/2025/07/AndroidFreqSend.pdf",
            "is_active": True,
            "order": 2,
            "applies_to_all": True,
        },
        {
            "product_identifier": "Einrichtungsanleitungen",
            "language": "de",
            "manual_type": "configuration",
            "title": "Anleitung Einrichtung neuer BLE Geräte in Sky-Map für iOS",
            "pdf_url": "https://sdlink.de/wp-content/uploads/2025/07/IOSSendFreq.pdf",
            "is_active": True,
            "order": 3,
            "applies_to_all": True,
        },

        # Englisch
        {
            "product_identifier": "Einrichtungsanleitungen",
            "language": "en",
            "manual_type": "configuration",
            "title": "How to add a new BLE adapter in SkyDemon",
            "pdf_url": "https://sdlink.de/wp-content/uploads/2025/02/How-to-Configure-a-New-SD-BLE-Adapter-in-SkyDemon-EN.pdf",
            "is_active": True,
            "order": 1,
            "applies_to_all": True,
        },

        # Französisch
        {
            "product_identifier": "Einrichtungsanleitungen",
            "language": "fr",
            "manual_type": "configuration",
            "title": "Comment configurer un nouveau SD dans SkyDemon",
            "pdf_url": "https://sdlink.de/wp-content/uploads/2025/03/Comment-configurer-un-nouveau-SD-dans-SkyDemon.pdf",
            "is_active": True,
            "order": 1,
            "applies_to_all": True,
        },

        # Spanisch (URL sicher URL-encodiert wegen „¿“)
        {
            "product_identifier": "Einrichtungsanleitungen",
            "language": "es",
            "manual_type": "configuration",
            "title": "Cómo añadir un nuevo adaptador BLE en SkyDemon",
            "pdf_url": "https://sdlink.de/wp-content/uploads/2025/06/%C2%BFComo-configuro-un-nuevo-adaptador-SD-BLE-en-SkyDemon.pdf",
            "is_active": True,
            "order": 1,
            "applies_to_all": True,
        },

        # =========================================================
        # PRODUKTSPEZIFISCHE INSTALLATIONSANLEITUNGEN
        # -> erscheinen nur, wenn das Produkt in der Bestellung ist
        # =========================================================

        # ----- SD-KRT2 -----
        {
            "product_identifier": "SD-KRT2",
            "language": "de",
            "manual_type": "installation",
            "title": "Installationsanleitung SD-KRT2",
            "pdf_url": "https://sdlink.de/wp-content/uploads/2025/01/Installation-SD-KRT2-E-V1.1.pdf",
            "is_active": True,
            "order": 10,
            "applies_to_all": False,
        },
        {
            "product_identifier": "SD-KRT2",
            "language": "en",
            "manual_type": "installation",
            "title": "Installation instructions for SD-KRT2",
            "pdf_url": "https://sdlink.de/wp-content/uploads/2025/02/Installation-SD-KRT2-E-V1.1-EN.pdf",
            "is_active": True,
            "order": 10,
            "applies_to_all": False,
        },
        {
            "product_identifier": "SD-KRT2",
            "language": "fr",
            "manual_type": "installation",
            "title": "Installation du Adaptateur SD-KRT2",
            "pdf_url": "https://sdlink.de/wp-content/uploads/2025/03/Installation-du-SD-KRT2-E-V1.2.pdf",
            "is_active": True,
            "order": 10,
            "applies_to_all": False,
        },
        {
            "product_identifier": "SD-KRT2",
            "language": "es",
            "manual_type": "installation",
            "title": "Instalación SD-KRT2",
            "pdf_url": "https://sdlink.de/wp-content/uploads/2025/07/Instalacion-SD-KRT2-E-V1.1.pdf",
            "is_active": True,
            "order": 10,
            "applies_to_all": False,
        },

        # ----- SD-KRT2 angled -----
        {
            "product_identifier": "SD-KRT2-A",
            "language": "de",
            "manual_type": "installation",
            "title": "Installationsanleitung SD-KRT2 angled",
            "pdf_url": "https://sdlink.de/wp-content/uploads/2025/01/Installation-SD-KRT2-A-V1.1.pdf",
            "is_active": True,
            "order": 11,
            "applies_to_all": False,
        },
        {
            "product_identifier": "SD-KRT2-A",
            "language": "en",
            "manual_type": "installation",
            "title": "Installation instructions for SD-KRT2 angled",
            "pdf_url": "https://sdlink.de/wp-content/uploads/2025/02/Installation-SD-KRT2-A-V1.1-EN.pdf",
            "is_active": True,
            "order": 11,
            "applies_to_all": False,
        },
        {
            "product_identifier": "SD-KRT2-A",
            "language": "fr",
            "manual_type": "installation",
            "title": "Installation du Adaptateur SD-KRT2 coudé",
            "pdf_url": "https://sdlink.de/wp-content/uploads/2025/03/Installation-du-SD-KRT2-A-V1.2.pdf",
            "is_active": True,
            "order": 11,
            "applies_to_all": False,
        },

        # ----- SD-KRT2 Dual Source -----
        {
            "product_identifier": "SD-KRT2-DS",
            "language": "de",
            "manual_type": "installation",
            "title": "Installationsanleitung SD-KRT2 Dual Source",
            "pdf_url": "https://sdlink.de/wp-content/uploads/2025/09/Installation-SD-KRT2-DS-V2.0.pdf",
            "is_active": True,
            "order": 12,
            "applies_to_all": False,
        },
        {
            "product_identifier": "SD-KRT2-DS",
            "language": "en",
            "manual_type": "installation",
            "title": "Installation instructions for SD-KRT2 Dual Source",
            "pdf_url": "https://sdlink.de/wp-content/uploads/2025/09/Installation-SD-KRT2-DS-V2.0-1.pdf",
            "is_active": True,
            "order": 12,
            "applies_to_all": False,
        },
        {
            "product_identifier": "SD-KRT2-DS",
            "language": "fr",
            "manual_type": "installation",
            "title": "Installation du Adaptateur SD-KRT2 DS",
            "pdf_url": "https://sdlink.de/wp-content/uploads/2025/09/Installation-SD-KRT2-DS-V2.0-2.pdf",
            "is_active": True,
            "order": 12,
            "applies_to_all": False,
        },

        # ----- SD-AR620X -----
        {
            "product_identifier": "SD-AR620X",
            "language": "de",
            "manual_type": "installation",
            "title": "Installationsanleitung SD-AR620X",
            "pdf_url": "https://sdlink.de/wp-content/uploads/2025/01/Installation-AR620X-V1.1.pdf",
            "is_active": True,
            "order": 13,
            "applies_to_all": False,
        },
        {
            "product_identifier": "SD-AR620X",
            "language": "en",
            "manual_type": "installation",
            "title": "Installation instructions for SD-AR620X",
            "pdf_url": "https://sdlink.de/wp-content/uploads/2025/02/Installation-AR620X-V1.1-EN.pdf",
            "is_active": True,
            "order": 13,
            "applies_to_all": False,
        },
        {
            "product_identifier": "SD-AR620X",
            "language": "fr",
            "manual_type": "installation",
            "title": "Installation du Adaptateur SD-AR620X",
            "pdf_url": "https://sdlink.de/wp-content/uploads/2025/03/Installation-du-SD-AR620X-V1.2.pdf",
            "is_active": True,
            "order": 13,
            "applies_to_all": False,
        },

        # ----- SD-AR620X-NG -----
        {
            "product_identifier": "SD-AR620X-NG",
            "language": "de",
            "manual_type": "installation",
            "title": "Installationsanleitung SD-AR620X-NG",
            "pdf_url": "https://sdlink.de/wp-content/uploads/2025/05/Installation-SD-AR620X-E-NG-V1.2-1.pdf",
            "is_active": True,
            "order": 14,
            "applies_to_all": False,
        },
        {
            "product_identifier": "SD-AR620X-NG",
            "language": "en",
            "manual_type": "installation",
            "title": "Installation instructions for SD-AR620X-NG",
            "pdf_url": "https://sdlink.de/wp-content/uploads/2025/05/Installation-du-SD-AR620X-E-NG-V1.2.pdf",
            "is_active": True,
            "order": 14,
            "applies_to_all": False,
        },
        {
            "product_identifier": "SD-AR620X-NG",
            "language": "fr",
            "manual_type": "installation",
            "title": "Installation du Adaptateur SD-AR620X-NG",
            "pdf_url": "https://sdlink.de/wp-content/uploads/2025/05/Installation-du-SD-AR620X-E-NG-V1.2-1.pdf",
            "is_active": True,
            "order": 14,
            "applies_to_all": False,
        },
        {
            "product_identifier": "SD-AR620X-NG",
            "language": "es",
            "manual_type": "installation",
            "title": "Instalación SD-AR620X-NG",
            "pdf_url": "https://sdlink.de/wp-content/uploads/2025/06/Instalacion-SD-AR620X-NG-V1.2.pdf",
            "is_active": True,
            "order": 14,
            "applies_to_all": False,
        },

        # ----- SD-ATR833 -----
        {
            "product_identifier": "SD-ATR833",
            "language": "de",
            "manual_type": "installation",
            "title": "Installationsanleitung SD-ATR833",
            "pdf_url": "https://sdlink.de/wp-content/uploads/2025/02/Installation-SD-ATR833-E-V1.1.pdf",
            "is_active": True,
            "order": 15,
            "applies_to_all": False,
        },
        {
            "product_identifier": "SD-ATR833",
            "language": "en",
            "manual_type": "installation",
            "title": "Installation instructions for SD-ATR833",
            "pdf_url": "https://sdlink.de/wp-content/uploads/2025/02/Installation-SD-ATR833-E-V1.1-EN.pdf",
            "is_active": True,
            "order": 15,
            "applies_to_all": False,
        },
        {
            "product_identifier": "SD-ATR833",
            "language": "fr",
            "manual_type": "installation",
            "title": "Installation du Adaptateur SD-ATR833",
            "pdf_url": "https://sdlink.de/wp-content/uploads/2025/03/Installation-du-SD-ATR833-E-V1.2.pdf",
            "is_active": True,
            "order": 15,
            "applies_to_all": False,
        },

        # ----- SD-ATR833 angled -----
        {
            "product_identifier": "SD-ATR833-A",
            "language": "de",
            "manual_type": "installation",
            "title": "Installationsanleitung SD-ATR833 angled",
            "pdf_url": "https://sdlink.de/wp-content/uploads/2025/03/Installation-SD-ATR833-A-V1.1.pdf",
            "is_active": True,
            "order": 16,
            "applies_to_all": False,
        },
        {
            "product_identifier": "SD-ATR833-A",
            "language": "en",
            "manual_type": "installation",
            "title": "Installation instructions for SD-ATR833 angled",
            "pdf_url": "https://sdlink.de/wp-content/uploads/2025/03/Installation-SD-ATR833-A-V1.1-EN.pdf",
            "is_active": True,
            "order": 16,
            "applies_to_all": False,
        },
        {
            "product_identifier": "SD-ATR833-A",
            "language": "fr",
            "manual_type": "installation",
            "title": "Installation du Adaptateur SD-ATR833 coudé",
            "pdf_url": "https://sdlink.de/wp-content/uploads/2025/03/Installation-du-SD-ATR833-A-V1.2.pdf",
            "is_active": True,
            "order": 16,
            "applies_to_all": False,
        },

        # ----- SD-ATR833 Dual Source -----
        {
            "product_identifier": "SD-ATR833-DS",
            "language": "de",
            "manual_type": "installation",
            "title": "Installationsanleitung SD-ATR833-DS",
            "pdf_url": "https://sdlink.de/wp-content/uploads/2025/10/GER_Installation-SD-ATR833-DS-V2.0.pdf",
            "is_active": True,
            "order": 17,
            "applies_to_all": False,
        },
        {
            "product_identifier": "SD-ATR833-DS",
            "language": "en",
            "manual_type": "installation",
            "title": "Installation instructions for SD-ATR833-DS",
            "pdf_url": "https://sdlink.de/wp-content/uploads/2025/10/EN_Installation-SD-ATR833-DS-V2.0.pdf",
            "is_active": True,
            "order": 17,
            "applies_to_all": False,
        },
        {
            "product_identifier": "SD-ATR833-DS",
            "language": "fr",
            "manual_type": "installation",
            "title": "Installation du Adaptateur SD-ATR833-DS",
            "pdf_url": "https://sdlink.de/wp-content/uploads/2025/10/FR_Installation-SD-ATR833-DS-V2.0.pdf",
            "is_active": True,
            "order": 17,
            "applies_to_all": False,
        },
        {
            "product_identifier": "SD-ATR833-DS",
            "language": "es",
            "manual_type": "installation",
            "title": "Instalación SD-ATR833-DS",
            "pdf_url": "https://sdlink.de/wp-content/uploads/2025/10/ES_Installation-SD-ATR833-DS-V2.0.pdf",
            "is_active": True,
            "order": 17,
            "applies_to_all": False,
        },

        # ----- SD-GENERIC -----
        {
            "product_identifier": "SD-GENERIC",
            "language": "de",
            "manual_type": "installation",
            "title": "Installationsanleitung SD-GENERIC",
            "pdf_url": "https://sdlink.de/wp-content/uploads/2025/01/Installation-SD-GENERIC-E-V1.1.pdf",
            "is_active": True,
            "order": 18,
            "applies_to_all": False,
        },
        {
            "product_identifier": "SD-GENERIC",
            "language": "en",
            "manual_type": "installation",
            "title": "Installation instructions for SD-GENERIC",
            "pdf_url": "https://sdlink.de/wp-content/uploads/2025/02/Installation-SD-GENERIC-E-V1-EN.pdf",
            "is_active": True,
            "order": 18,
            "applies_to_all": False,
        },
        {
            "product_identifier": "SD-GENERIC",
            "language": "fr",
            "manual_type": "installation",
            "title": "Installation du Adaptateur SD-GENERIC",
            "pdf_url": "https://sdlink.de/wp-content/uploads/2025/03/Installation-SD-GENERIC-E-V1.pdf",
            "is_active": True,
            "order": 18,
            "applies_to_all": False,
        },
        {
            "product_identifier": "SD-GENERIC",
            "language": "es",
            "manual_type": "installation",
            "title": "Instalación SD-GENERIC",
            "pdf_url": "https://sdlink.de/wp-content/uploads/2025/06/Instalacion-SD-GENERIC-E-V1.pdf",
            "is_active": True,
            "order": 18,
            "applies_to_all": False,
        },

        # ----- SD-GENERIC Dual Source -----
        {
            "product_identifier": "SD-GENERIC-DS",
            "language": "de",
            "manual_type": "installation",
            "title": "Installationsanleitung SD-GENERIC-DS",
            "pdf_url": "https://sdlink.de/wp-content/uploads/2025/09/Installation-SD-GENERIC-DS-V2.0.pdf",
            "is_active": True,
            "order": 19,
            "applies_to_all": False,
        },
        {
            "product_identifier": "SD-GENERIC-DS",
            "language": "en",
            "manual_type": "installation",
            "title": "Installation instructions for SD-GENERIC-DS",
            "pdf_url": "https://sdlink.de/wp-content/uploads/2025/09/Installation-SD-GENERIC-DS-V2.0-1.pdf",
            "is_active": True,
            "order": 19,
            "applies_to_all": False,
        },
        {
            "product_identifier": "SD-GENERIC-DS",
            "language": "fr",
            "manual_type": "installation",
            "title": "Installation du Adaptateur SD-GENERIC-DS",
            "pdf_url": "https://sdlink.de/wp-content/uploads/2025/09/Installation-SD-GENERIC-DS-V2.pdf",
            "is_active": True,
            "order": 19,
            "applies_to_all": False,
        },
        {
            "product_identifier": "SD-GENERIC-DS",
            "language": "es",
            "manual_type": "installation",
            "title": "Instalación SD-GENERIC-DS",
            "pdf_url": "https://sdlink.de/wp-content/uploads/2025/09/Installation-SD-GENERIC-DS-V2-1.pdf",
            "is_active": True,
            "order": 19,
            "applies_to_all": False,
        },

        # ----- SD-TY9X -----
        {
            "product_identifier": "SD-TY9X",
            "language": "de",
            "manual_type": "installation",
            "title": "Installationsanleitung SD-TRIG TY9X",
            "pdf_url": "https://sdlink.de/wp-content/uploads/2025/05/Installation-SD-TY9X-E-V1.2-1-1.pdf",
            "is_active": True,
            "order": 20,
            "applies_to_all": False,
        },
        {
            "product_identifier": "SD-TY9X",
            "language": "en",
            "manual_type": "installation",
            "title": "Installation instructions for SD-TY9X",
            "pdf_url": "https://sdlink.de/wp-content/uploads/2025/05/Installation-SD-TY9X-E-V1.2-1-2.pdf",
            "is_active": True,
            "order": 20,
            "applies_to_all": False,
        },
        {
            "product_identifier": "SD-TY9X",
            "language": "fr",
            "manual_type": "installation",
            "title": "Installation du Adaptateur SD-TY9X",
            "pdf_url": "https://sdlink.de/wp-content/uploads/2025/05/Installation-SD-TY9X-E-V1.2-1-3.pdf",
            "is_active": True,
            "order": 20,
            "applies_to_all": False,
        },

        # ----- SD-TY96/TY97 Dual Source -----
        {
            "product_identifier": "SD-TY96_TY97-DS",
            "language": "de",
            "manual_type": "installation",
            "title": "Installationsanleitung SD-TY96/TY97-DS",
            "pdf_url": "https://sdlink.de/wp-content/uploads/2025/10/DE_Installation-SD-TY96_TY97-DS-V2.0.pdf",
            "is_active": True,
            "order": 21,
            "applies_to_all": False,
        },
        {
            "product_identifier": "SD-TY96_TY97-DS",
            "language": "en",
            "manual_type": "installation",
            "title": "Installation instructions for SD-TY96/TY97-DS",
            "pdf_url": "https://sdlink.de/wp-content/uploads/2025/10/EN_Installation-SD-TY96_TY97-DS-V2.0.pdf",
            "is_active": True,
            "order": 21,
            "applies_to_all": False,
        },

        # ----- SD-AV-30-E -----
        {
            "product_identifier": "SD-AV-30-E",
            "language": "de",
            "manual_type": "installation",
            "title": "Installationsanleitung SD-AV-30-E",
            "pdf_url": "https://sdlink.de/wp-content/uploads/2025/05/Installation-SD-AV-30-E-V1.2.pdf",
            "is_active": True,
            "order": 22,
            "applies_to_all": False,
        },
        {
            "product_identifier": "SD-AV-30-E",
            "language": "en",
            "manual_type": "installation",
            "title": "Installation instruction SD-AV-30-E",
            "pdf_url": "https://sdlink.de/wp-content/uploads/2025/05/Installation-SD-AV-30-E-V1.2-1.pdf",
            "is_active": True,
            "order": 22,
            "applies_to_all": False,
        },
    ]

    ProductManual.objects.bulk_create([ProductManual(**m) for m in manuals])


def reverse_populate_product_manuals(apps, schema_editor):
    """Remove all product manuals."""
    ProductManual = apps.get_model('shopbridge', 'ProductManual')
    ProductManual.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("shopbridge", "0007_add_applies_to_all_field"),
    ]

    operations = [
        migrations.RunPython(
            populate_product_manuals,
            reverse_populate_product_manuals,
        ),
    ]