# Generated by Django 5.2 on 2025-11-29 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopbridge', '0008_populate_product_manuals'),
    ]

    operations = [
    ]
