# Generated by Django 5.2 on 2025-11-29 06:06

from django.db import migrations


def migrate_warenpost_to_kleinpaket(apps, schema_editor):
    """
    Migriert alle V62WP (Warenpost National) Einträge zu V62KP (DHL Kleinpaket).
    
    Warenpost (V62WP) wurde zum 1.1.2025 von DHL eingestellt und durch
    DHL Kleinpaket (V62KP) ersetzt.
    """
    # Migrate ShippingCountryConfig
    ShippingCountryConfig = apps.get_model('shopbridge', 'ShippingCountryConfig')
    updated_configs = ShippingCountryConfig.objects.filter(
        dhl_product='V62WP'
    ).update(dhl_product='V62KP')
    
    if updated_configs:
        print(f"  Migrated {updated_configs} ShippingCountryConfig(s) from V62WP to V62KP")
    
    # Migrate DHLLabel (falls vorhanden)
    try:
        DHLLabel = apps.get_model('shopbridge', 'DHLLabel')
        updated_labels = DHLLabel.objects.filter(
            product='V62WP'
        ).update(product='V62KP')
        
        if updated_labels:
            print(f"  Migrated {updated_labels} DHLLabel(s) from V62WP to V62KP")
    except LookupError:
        pass  # DHLLabel model doesn't exist yet


def reverse_migration(apps, schema_editor):
    """Reverse migration - converts V62KP back to V62WP (nicht empfohlen)."""
    # This is intentionally a no-op since we don't want to revert to deprecated product
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('shopbridge', '0009_migrate_warenpost_to_kleinpaket'),
    ]

    operations = [
        migrations.RunPython(
            migrate_warenpost_to_kleinpaket,
            reverse_code=reverse_migration
        ),
    ]
