from django.urls import path
from .views import (
    DeliveryDetailView,
    DeliveryListCreateView,
    MaterialAlternativesView,
    MaterialCategoryDetailView,
    MaterialCategoryListCreateView,
    MaterialDetailView,
    MaterialListCreateView,
    MaterialMovementDetailView,
    MaterialMovementListCreateView,
    MaterialTransferDetailView,
    MaterialTransferListCreateView,
    OrderDeliveriesListView,
    OrderDetailView,
    OrderListCreateView,
    SupplierDetailView,
    SupplierListCreateView,
    MaterialSupplierPriceListCreateView,
    MaterialSupplierPriceDetailView,
    all_materials_stock_by_workshop,
    material_stock_view,
    material_inventory_correction_view,
    material_products_view,
    toggle_material_deprecated,
    material_supplier_prices_overview,
    export_suppliers,
    import_suppliers,
    export_orders,
    import_orders,
    export_material_supplier_prices,
    import_material_supplier_prices,
)

urlpatterns = [
    path("suppliers/", SupplierListCreateView.as_view(), name="supplier-list-create"),
    path("suppliers/<int:pk>/", SupplierDetailView.as_view(), name="supplier-detail"),
    path("materials/", MaterialListCreateView.as_view()),
    path("materials/<int:pk>/", MaterialDetailView.as_view(), name="material-detail"),
    path("materials/<int:material_id>/movements/", MaterialMovementListCreateView.as_view()),
    path("materials/<int:material_id>/movements/<int:pk>/", MaterialMovementDetailView.as_view()),
    path("material-categories/", MaterialCategoryListCreateView.as_view(), name="material-category-list-create"),
    path("material-categories/<int:pk>/", MaterialCategoryDetailView.as_view(), name="material-category-detail"),
    path("materials/<int:pk>/alternatives/", MaterialAlternativesView.as_view(), name="material-alternatives"),
    path("materials/<int:pk>/alternatives/<int:alternative_pk>/", MaterialAlternativesView.as_view(), name="material-alternatives-delete"),
    path("transfers/", MaterialTransferListCreateView.as_view(), name="transfer-list-create"),
    path("transfers/<int:pk>/", MaterialTransferDetailView.as_view(), name="transfer-detail"),
    path("deliveries/", DeliveryListCreateView.as_view(), name="delivery-list-create"),
    path("deliveries/<int:pk>/", DeliveryDetailView.as_view(), name="delivery-detail"),
    path("orders/", OrderListCreateView.as_view(), name="order-list-create"),
    path("orders/<int:pk>/", OrderDetailView.as_view(), name="order-detail"),
    path("orders/<int:pk>/deliveries/", OrderDeliveriesListView.as_view(), name="order-deliveries"),
    path("materials/<int:material_id>/stock/", material_stock_view, name="material-stock"),
    path("workshops/<int:workshop_id>/material-stock/", 
         all_materials_stock_by_workshop, 
         name="workshop-material-stock"),
    path("materials/<int:material_id>/inventory-correction/",
         material_inventory_correction_view,
         name="material-inventory-correction"),
    path("materials/<int:material_id>/products/",
         material_products_view,
         name="material-products"),
    path("materials/<int:material_id>/toggle-deprecated/",
         toggle_material_deprecated,
         name="toggle-material-deprecated"),
    # Material Supplier Prices
    path("material-supplier-prices/",
         MaterialSupplierPriceListCreateView.as_view(),
         name="material-supplier-price-list-create"),
    path("material-supplier-prices/<int:pk>/",
         MaterialSupplierPriceDetailView.as_view(),
         name="material-supplier-price-detail"),
    path("materials/<int:material_id>/supplier-prices/",
         material_supplier_prices_overview,
         name="material-supplier-prices-overview"),
    # Export/Import endpoints
    path("suppliers/export/",
         export_suppliers,
         name="suppliers-export"),
    path("suppliers/import/",
         import_suppliers,
         name="suppliers-import"),
    path("orders/export/",
         export_orders,
         name="orders-export"),
    path("orders/import/",
         import_orders,
         name="orders-import"),
    path("material-supplier-prices/export/",
         export_material_supplier_prices,
         name="material-supplier-prices-export"),
    path("material-supplier-prices/import/",
         import_material_supplier_prices,
         name="material-supplier-prices-import"),
]
