# Generated by Django 5.2 on 2025-04-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='version',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
