# Generated by Django 5.2.8 on 2025-11-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_duplicate_productmaterials'),
        ('materials', '0008_alter_materialmovement_change_type'),
        ('products', '0002_productvariant_product_varianten'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productstock',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='product',
            name='deprecated',
            field=models.BooleanField(default=False, help_text='Produkt ist veraltet und wird nicht mehr verwendet'),
        ),
        migrations.AddConstraint(
            model_name='productmaterial',
            constraint=models.UniqueConstraint(fields=('product', 'material'), name='unique_product_material'),
        ),
        migrations.AddConstraint(
            model_name='productstock',
            constraint=models.UniqueConstraint(fields=('workshop', 'product'), name='unique_workshop_product_stock'),
        ),
    ]
